// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGuR6d1jSC8EOGvTcYmfOu51SKN3OT7Rs',
    appId: '1:561584619861:web:c03d4ddc0426b72c33afdc',
    messagingSenderId: '561584619861',
    projectId: 'smart-trip-planner-e4fe2',
    authDomain: 'smart-trip-planner-e4fe2.firebaseapp.com',
    storageBucket: 'smart-trip-planner-e4fe2.firebasestorage.app',
    measurementId: 'G-XSDHHVBPE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hGCOUmiLp20xqRRjV457LPqOXC2jZ2E',
    appId: '1:561584619861:android:3f82891511f972b233afdc',
    messagingSenderId: '561584619861',
    projectId: 'smart-trip-planner-e4fe2',
    storageBucket: 'smart-trip-planner-e4fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiy0HdFqgCYW-kUxwdNWlOZPkX2PMeR0U',
    appId: '1:561584619861:ios:857c66bf517e16a433afdc',
    messagingSenderId: '561584619861',
    projectId: 'smart-trip-planner-e4fe2',
    storageBucket: 'smart-trip-planner-e4fe2.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiy0HdFqgCYW-kUxwdNWlOZPkX2PMeR0U',
    appId: '1:561584619861:ios:857c66bf517e16a433afdc',
    messagingSenderId: '561584619861',
    projectId: 'smart-trip-planner-e4fe2',
    storageBucket: 'smart-trip-planner-e4fe2.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGuR6d1jSC8EOGvTcYmfOu51SKN3OT7Rs',
    appId: '1:561584619861:web:2a575cf56a0e3ba233afdc',
    messagingSenderId: '561584619861',
    projectId: 'smart-trip-planner-e4fe2',
    authDomain: 'smart-trip-planner-e4fe2.firebaseapp.com',
    storageBucket: 'smart-trip-planner-e4fe2.firebasestorage.app',
    measurementId: 'G-7PB3C4N38F',
  );
}
